---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	normalize_text(normalize_text)
	analyze_text(analyze_text)
	review_text_with_ai(review_text_with_ai)
	suggest_improvement(suggest_improvement)
	create_report(create_report)
	__end__([<p>__end__</p>]):::last
	__start__ --> normalize_text;
	analyze_text --> review_text_with_ai;
	normalize_text --> analyze_text;
	review_text_with_ai -.-> create_report;
	review_text_with_ai -.-> suggest_improvement;
	suggest_improvement --> create_report;
	create_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
